name: Manga Download and Upload

on:
  workflow_dispatch:
    inputs:
      reset_index:
        description: 'Set to true to reset index to 1'
        required: false
        default: 'false'

permissions:
  contents: write

jobs:
  download_and_upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Tmate (Background SSH Access)
        run: |
          sudo apt-get update
          sudo apt-get install -y tmate
          tmate -S /tmp/tmate.sock new-session -d
          tmate -S /tmp/tmate.sock wait tmate-ready
          tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}' > tmate_ssh_url.txt
          tmate -S /tmp/tmate.sock display -p '#{tmate_web}' > tmate_web_url.txt
          echo "Tmate SSH URL: $(cat tmate_ssh_url.txt)"
          echo "Tmate Web URL: $(cat tmate_web_url.txt)"

      - name: Display Tmate Connection Info
        run: |
          echo "Access the session via SSH or web URL provided below:"
          echo "SSH: $(cat tmate_ssh_url.txt)"
          echo "Web: $(cat tmate_web_url.txt)"

      - name: Install Mangadex Downloader and Rclone
        run: |
          pip install mangadex-downloader
          sudo apt-get install -y rclone

      - name: Determine Starting Index
        id: determine_index
        run: |
          if [[ "${{ github.event.inputs.reset_index }}" == "true" ]]; then
            echo "Resetting index to 1."
            echo "1" > last_index.txt
          elif [[ -f last_index.txt ]]; then
            last_index=$(cat last_index.txt)
            echo "$((last_index + 1))" > last_index.txt
          else
            echo "1" > last_index.txt
          fi
          echo "Starting index: $(cat last_index.txt)"

      - name: Get the Next URL
        id: get_url
        run: |
          current_index=$(cat last_index.txt)
          echo "Fetching URL from line ${current_index}."
          sed -n "${current_index}p" manga.txt > current_url.txt
          if [[ ! -s current_url.txt ]]; then
            echo "No URL found at line ${current_index}. Exiting."
            exit 0
          fi
          echo "URL to download:"
          cat current_url.txt

      - name: Download Manga
        run: |
          # Download the manga from the single URL
          mangadex-dl $(cat current_url.txt) --no-group-name -d manga --progress-bar-layout=none -wti

      - name: Determine Folder Name
        id: folder_name
        run: |
          # List all items in the `manga` directory to identify the folder name
          ls -la manga
          
          # Find the exact folder name created by `mangadex-dl` (there should only be one folder)
          manga_folder=$(ls manga)
          echo "${manga_folder}" > folder_name.txt
          
          # Sanitize the folder name for the archive (remove spaces, lowercase)
          sanitized_folder_name=$(echo "${manga_folder}" | tr -d ' ' | tr '[:upper:]' '[:lower:]')
          echo "${sanitized_folder_name}" > archive_name.txt
          echo "Detected folder name: '${manga_folder}', Sanitized archive name: '${sanitized_folder_name}'"

      - name: Archive Manga Folder
        run: |
          # Use the exact folder name in the `tar` command and the sanitized name for the archive
          manga_folder=$(cat folder_name.txt)
          archive_name=$(cat archive_name.txt)
          echo "Archiving folder '${manga_folder}' to '${archive_name}.tar'"
          tar -cf "${archive_name}.tar" -C manga "${manga_folder}"
          echo "Archive created: ${archive_name}.tar"

      - name: Upload to Google Drive
        env:
          RCLONE_CONFIG_DATA: ${{ secrets.RCLONE_CONFIG }}
        run: |
          echo "${RCLONE_CONFIG_DATA}" > /tmp/rclone.conf
          archive_name=$(cat archive_name.txt)
          rclone --config /tmp/rclone.conf move "${archive_name}.tar" 300:manga/
          echo "Uploaded ${archive_name}.tar to Google Drive"

      - name: Send Telegram Notification
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          current_index=$(cat last_index.txt)
          archive_name=$(cat archive_name.txt)
          message="Manga '${archive_name}' from index ${current_index} uploaded successfully."
          curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage" -d chat_id="${TELEGRAM_CHAT_ID}" -d text="${message}"

      - name: Commit Updated Index
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add last_index.txt
          git commit -m "Update last processed index to $(cat last_index.txt)"
          git push "https://${GITHUB_TOKEN}@github.com/${{ github.repository }}.git" main

      - name: Wait for Background Jobs
        run: |
          # Wait for any background jobs to complete before finishing
          wait
