name: Manga Download and Upload

on:
  workflow_dispatch:
    inputs:
      reset_index:
        description: 'Set to true to reset index to 1'
        required: false
        default: 'false'
  schedule:
    - cron: "0 0 * * *"

jobs:
  download_and_upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Mangadex Downloader and Rclone
        run: |
          pip install mangadex-downloader
          sudo apt-get install -y rclone

      - name: Determine Starting Index
        id: determine_index
        run: |
          if [[ "${{ github.event.inputs.reset_index }}" == "true" ]]; then
            echo "Resetting index to 1."
            echo "1" > last_index.txt
          elif [[ -f last_index.txt ]]; then
            last_index=$(cat last_index.txt)
            echo "$((last_index + 1))" > last_index.txt
          else
            echo "1" > last_index.txt
          fi
          echo "Starting index: $(cat last_index.txt)"

      - name: Get the Next URL
        id: get_url
        run: |
          start_index=$(cat last_index.txt)
          echo "Fetching URL at line ${start_index}."
          sed -n "${start_index}p" manga.txt > current_batch.txt
          if [[ ! -s current_batch.txt ]]; then
            echo "No URL found at line ${start_index}. Exiting."
            exit 0
          fi
          echo "URL to download: $(cat current_batch.txt)"

      - name: Download Manga
        run: mangadex-dl current_batch.txt --no-group-name -d manga -f cbz --progress-bar-layout=none -wti

      - name: Archive Manga Folder
        run: |
          timestamp=$(date +'%Y%m%d%H%M%S')
          tar -cf "${timestamp}.tar" -C manga .
          echo "Archive created: ${timestamp}.tar"

      - name: Upload to Google Drive
        env:
          RCLONE_CONFIG_DATA: ${{ secrets.RCLONE_CONFIG }}
        run: |
          # Write the RCLONE_CONFIG data to a temporary file
          echo "${RCLONE_CONFIG_DATA}" > /tmp/rclone.conf
          # Use the temporary config file for the rclone command
          timestamp=$(date +'%Y%m%d%H%M%S')
          rclone --config /tmp/rclone.conf move "${timestamp}.tar" 300:manga/

      - name: Send Telegram Notification
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          start_index=$(cat last_index.txt)
          message="Manga at index ${start_index} uploaded successfully."
          curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage" -d chat_id="${TELEGRAM_CHAT_ID}" -d text="${message}"

      - name: Commit Updated Index
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git add last_index.txt
          git commit -m "Update last processed index to $(cat last_index.txt)"
          git push
